# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow_db
spring.datasource.username=postgres
spring.datasource.password=Root@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
taskflow.jwt.secret=9a67475357326577313832343536373839303132333435363738393031323334353637383930313233343536373839303132333435363738393031323334353637383930
taskflow.jwt.expiration=86400000

# Server Configuration
server.port=8080

# Logging
logging.level.org.springframework.security=DEBUG
